import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProviders } from "./ThemeProviders";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
/**/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-zinc-100 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100">
        <ThemeProviders>
          <div className="flex flex-col ">
            <Navbar />
            {children}
          </div>
        </ThemeProviders>
      </body>
    </html>
  );
}
