# Dockerfile

FROM python:3-slim

WORKDIR /app

COPY requirements.txt requirements.txt

# Update distribution
RUN apt-get update \
    # Install dependencies required for psycopg2 to compile
    && apt-get -y install libpq-dev gcc \
    # Install all the pip modules
    && pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]